name: Publish new documentation

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Build and deploy documentation
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        ./deploy
