name: Publish new documentation

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.10
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.10
    - name: Build and push documentation
      env:
        GIT_DEPLOY_USERNAME: Github Action
        GIT_DEPLOY_EMAIL: action@github.com
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gem install bundler:1.17.3
        bundle install --jobs 4 --retry 3
        ./deploy.sh --github-action
