name: Publish new documentation

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.5
    - name: Build documentation
      env:
        GIT_DEPLOY_USERNAME: Github Action
        GIT_DEPLOY_EMAIL: action@github.com
      run: |
        gem install bundler:1.17.1
        bundle install --jobs 4 --retry 3
         ./deploy.sh --commit-only
    - name: Push documentation
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
